[2024-01-27T20:56:20.921+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-01-27T20:55:58.563134+00:00 [queued]>
[2024-01-27T20:56:20.947+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-01-27T20:55:58.563134+00:00 [queued]>
[2024-01-27T20:56:20.947+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-27T20:56:20.947+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-01-27T20:56:20.947+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-27T20:56:20.997+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-01-27 20:55:58.563134+00:00
[2024-01-27T20:56:21.011+0000] {standard_task_runner.py:55} INFO - Started process 807 to run task
[2024-01-27T20:56:21.021+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2024-01-27T20:55:58.563134+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpowpy2q_w']
[2024-01-27T20:56:21.021+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask tsk4
[2024-01-27T20:56:21.220+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2024-01-27T20:55:58.563134+00:00 [running]> on host 5b3777e64f6c
[2024-01-27T20:56:21.421+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-01-27T20:55:58.563134+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-27T20:55:58.563134+00:00
[2024-01-27T20:56:21.422+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-27T20:56:21.423+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-27T20:56:21.445+0000] {subprocess.py:86} INFO - Output:
[2024-01-27T20:56:21.452+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-27T20:56:21.478+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-27T20:56:21.486+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=email_test, task_id=tsk4, execution_date=20240127T205558, start_date=20240127T205620, end_date=20240127T205621
[2024-01-27T20:56:21.523+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 108 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 807)
[2024-01-27T20:56:21.552+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-27T20:56:21.618+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
