[2024-01-29T21:15:23.543+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-29T12:00:00+00:00 [queued]>
[2024-01-29T21:15:23.575+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-29T12:00:00+00:00 [queued]>
[2024-01-29T21:15:23.575+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-29T21:15:23.576+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-29T21:15:23.576+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-29T21:15:23.614+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-01-29 12:00:00+00:00
[2024-01-29T21:15:23.621+0000] {standard_task_runner.py:55} INFO - Started process 92 to run task
[2024-01-29T21:15:23.631+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-01-29T12:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpxi3lx26n']
[2024-01-29T21:15:23.632+0000] {standard_task_runner.py:83} INFO - Job 338: Subtask tsk4
[2024-01-29T21:15:23.898+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-01-29T12:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-01-29T21:15:24.083+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-01-29T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-29T12:00:00+00:00
[2024-01-29T21:15:24.088+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-29T21:15:24.088+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-29T21:15:24.106+0000] {subprocess.py:86} INFO - Output:
[2024-01-29T21:15:24.114+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-29T21:15:24.147+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-29T21:15:24.154+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20240129T120000, start_date=20240129T211523, end_date=20240129T211524
[2024-01-29T21:15:24.198+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 338 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 92)
[2024-01-29T21:15:24.228+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-29T21:15:24.289+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
