[2024-01-30T10:35:24.232+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-30T09:00:00+00:00 [queued]>
[2024-01-30T10:35:24.250+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-30T09:00:00+00:00 [queued]>
[2024-01-30T10:35:24.251+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-30T10:35:24.251+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-30T10:35:24.251+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-30T10:35:24.279+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-01-30 09:00:00+00:00
[2024-01-30T10:35:24.286+0000] {standard_task_runner.py:55} INFO - Started process 4265 to run task
[2024-01-30T10:35:24.291+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-01-30T09:00:00+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpf940jqlo']
[2024-01-30T10:35:24.292+0000] {standard_task_runner.py:83} INFO - Job 363: Subtask tsk4
[2024-01-30T10:35:24.398+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-01-30T09:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-01-30T10:35:24.564+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-01-30T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-30T09:00:00+00:00
[2024-01-30T10:35:24.565+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-30T10:35:24.566+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-30T10:35:24.586+0000] {subprocess.py:86} INFO - Output:
[2024-01-30T10:35:24.592+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-30T10:35:24.618+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-30T10:35:24.625+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20240130T090000, start_date=20240130T103524, end_date=20240130T103524
[2024-01-30T10:35:24.648+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 363 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 4265)
[2024-01-30T10:35:24.665+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-30T10:35:24.724+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
