[2024-01-28T13:00:05.695+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-28T12:00:00+00:00 [queued]>
[2024-01-28T13:00:05.714+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-01-28T12:00:00+00:00 [queued]>
[2024-01-28T13:00:05.714+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-28T13:00:05.714+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-01-28T13:00:05.715+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-28T13:00:05.732+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-01-28 12:00:00+00:00
[2024-01-28T13:00:05.738+0000] {standard_task_runner.py:55} INFO - Started process 54290 to run task
[2024-01-28T13:00:05.741+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-01-28T12:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmptl8b6pg1']
[2024-01-28T13:00:05.742+0000] {standard_task_runner.py:83} INFO - Job 266: Subtask tsk4
[2024-01-28T13:00:05.827+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-01-28T12:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-01-28T13:00:05.919+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-01-28T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-28T12:00:00+00:00
[2024-01-28T13:00:05.920+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-28T13:00:05.920+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-28T13:00:05.932+0000] {subprocess.py:86} INFO - Output:
[2024-01-28T13:00:05.935+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-28T13:00:05.950+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-28T13:00:05.955+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20240128T120000, start_date=20240128T130005, end_date=20240128T130005
[2024-01-28T13:00:05.970+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 266 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 54290)
[2024-01-28T13:00:05.993+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-28T13:00:06.026+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
