[2024-02-03T18:34:30.352+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-02-02T12:00:00+00:00 [queued]>
[2024-02-03T18:34:30.384+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-02-02T12:00:00+00:00 [queued]>
[2024-02-03T18:34:30.385+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-03T18:34:30.385+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-02-03T18:34:30.385+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-03T18:34:30.416+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-02-02 12:00:00+00:00
[2024-02-03T18:34:30.423+0000] {standard_task_runner.py:55} INFO - Started process 89 to run task
[2024-02-03T18:34:30.431+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-02-02T12:00:00+00:00', '--job-id', '580', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmplagpdkt4']
[2024-02-03T18:34:30.432+0000] {standard_task_runner.py:83} INFO - Job 580: Subtask tsk4
[2024-02-03T18:34:30.547+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-02-02T12:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-02-03T18:34:30.675+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T12:00:00+00:00
[2024-02-03T18:34:30.677+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-02-03T18:34:30.678+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-02-03T18:34:30.695+0000] {subprocess.py:86} INFO - Output:
[2024-02-03T18:34:30.701+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-03T18:34:30.725+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-03T18:34:30.733+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20240202T120000, start_date=20240203T183430, end_date=20240203T183430
[2024-02-03T18:34:30.764+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 580 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 89)
[2024-02-03T18:34:30.806+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-03T18:34:30.869+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
