[2024-01-24T00:52:55.359+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerDag2.tsk1 manual__2024-01-24T00:52:53.558046+00:00 [queued]>
[2024-01-24T00:52:55.402+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerDag2.tsk1 manual__2024-01-24T00:52:53.558046+00:00 [queued]>
[2024-01-24T00:52:55.403+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T00:52:55.404+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-24T00:52:55.404+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T00:52:55.448+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-01-24 00:52:53.558046+00:00
[2024-01-24T00:52:55.461+0000] {standard_task_runner.py:55} INFO - Started process 2419 to run task
[2024-01-24T00:52:55.472+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerDag2', 'tsk1', 'manual__2024-01-24T00:52:53.558046+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag2.py', '--cfg-path', '/tmp/tmpbkflvl6n']
[2024-01-24T00:52:55.473+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask tsk1
[2024-01-24T00:52:55.648+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerDag2.tsk1 manual__2024-01-24T00:52:53.558046+00:00 [running]> on host cd1b9fd02609
[2024-01-24T00:52:55.877+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerDag2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T00:52:53.558046+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-24T00:52:53.558046+00:00
[2024-01-24T00:52:55.879+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T00:52:55.880+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-24T00:52:55.899+0000] {subprocess.py:86} INFO - Output:
[2024-01-24T00:52:55.905+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T00:52:55.932+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T00:52:55.945+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerDag2, task_id=tsk1, execution_date=20240124T005253, start_date=20240124T005255, end_date=20240124T005255
[2024-01-24T00:52:55.981+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 2419)
[2024-01-24T00:52:56.018+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-24T00:52:56.069+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
