[2024-02-12T11:40:42.856+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigdata.big_data manual__2024-02-12T11:40:37.731478+00:00 [queued]>
[2024-02-12T11:40:42.929+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigdata.big_data manual__2024-02-12T11:40:37.731478+00:00 [queued]>
[2024-02-12T11:40:42.929+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-12T11:40:42.929+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-02-12T11:40:42.930+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-12T11:40:42.970+0000] {taskinstance.py:1300} INFO - Executing <Task(BigDataOperator): big_data> on 2024-02-12 11:40:37.731478+00:00
[2024-02-12T11:40:42.981+0000] {standard_task_runner.py:55} INFO - Started process 1107 to run task
[2024-02-12T11:40:42.993+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bigdata', 'big_data', 'manual__2024-02-12T11:40:37.731478+00:00', '--job-id', '1052', '--raw', '--subdir', 'DAGS_FOLDER/bigdata.py', '--cfg-path', '/tmp/tmpla2hesgr']
[2024-02-12T11:40:42.997+0000] {standard_task_runner.py:83} INFO - Job 1052: Subtask big_data
[2024-02-12T11:40:43.212+0000] {task_command.py:388} INFO - Running <TaskInstance: bigdata.big_data manual__2024-02-12T11:40:37.731478+00:00 [running]> on host 253264584ea3
[2024-02-12T11:40:43.590+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bigdata
AIRFLOW_CTX_TASK_ID=big_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-12T11:40:37.731478+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-12T11:40:37.731478+00:00
[2024-02-12T11:40:43.591+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in execute
    raise NotImplementedError()
NotImplementedError
[2024-02-12T11:40:43.611+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bigdata, task_id=big_data, execution_date=20240212T114037, start_date=20240212T114042, end_date=20240212T114043
[2024-02-12T11:40:43.655+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1052 for task big_data (; 1107)
[2024-02-12T11:40:43.709+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-12T11:40:43.762+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
