[2024-02-12T11:52:40.215+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigdata.big_data manual__2024-02-12T11:52:37.886523+00:00 [queued]>
[2024-02-12T11:52:40.233+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigdata.big_data manual__2024-02-12T11:52:37.886523+00:00 [queued]>
[2024-02-12T11:52:40.234+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-12T11:52:40.234+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-02-12T11:52:40.234+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-12T11:52:40.254+0000] {taskinstance.py:1300} INFO - Executing <Task(BigDataOperator): big_data> on 2024-02-12 11:52:37.886523+00:00
[2024-02-12T11:52:40.268+0000] {standard_task_runner.py:55} INFO - Started process 1588 to run task
[2024-02-12T11:52:40.274+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bigdata', 'big_data', 'manual__2024-02-12T11:52:37.886523+00:00', '--job-id', '1055', '--raw', '--subdir', 'DAGS_FOLDER/bigdata.py', '--cfg-path', '/tmp/tmp34zpa2m9']
[2024-02-12T11:52:40.277+0000] {standard_task_runner.py:83} INFO - Job 1055: Subtask big_data
[2024-02-12T11:52:40.361+0000] {task_command.py:388} INFO - Running <TaskInstance: bigdata.big_data manual__2024-02-12T11:52:37.886523+00:00 [running]> on host 253264584ea3
[2024-02-12T11:52:40.460+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bigdata
AIRFLOW_CTX_TASK_ID=big_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-12T11:52:37.886523+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-12T11:52:37.886523+00:00
[2024-02-12T11:52:40.461+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1113, in execute
    raise NotImplementedError()
NotImplementedError
[2024-02-12T11:52:40.473+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bigdata, task_id=big_data, execution_date=20240212T115237, start_date=20240212T115240, end_date=20240212T115240
[2024-02-12T11:52:40.487+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1055 for task big_data (; 1588)
[2024-02-12T11:52:40.524+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-12T11:52:40.552+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
