[2024-02-05T11:00:41.289+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.send_email scheduled__2024-02-05T10:00:00+00:00 [queued]>
[2024-02-05T11:00:41.354+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.send_email scheduled__2024-02-05T10:00:00+00:00 [queued]>
[2024-02-05T11:00:41.354+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T11:00:41.354+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-02-05T11:00:41.354+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T11:00:41.393+0000] {taskinstance.py:1300} INFO - Executing <Task(EmailOperator): send_email> on 2024-02-05 10:00:00+00:00
[2024-02-05T11:00:41.400+0000] {standard_task_runner.py:55} INFO - Started process 153 to run task
[2024-02-05T11:00:41.408+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'send_email', 'scheduled__2024-02-05T10:00:00+00:00', '--job-id', '753', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpakwlwg6p']
[2024-02-05T11:00:41.409+0000] {standard_task_runner.py:83} INFO - Job 753: Subtask send_email
[2024-02-05T11:00:41.557+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.send_email scheduled__2024-02-05T10:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-02-05T11:00:41.722+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T10:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-05T10:00:00+00:00
[2024-02-05T11:00:41.744+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-05T11:00:41.745+0000] {email.py:268} INFO - Email alerting: attempt 1
[2024-02-05T11:00:41.747+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
[2024-02-05T11:00:41.781+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=send_email, execution_date=20240205T100000, start_date=20240205T110041, end_date=20240205T110041
[2024-02-05T11:00:41.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 753 for task send_email ([Errno -3] Temporary failure in name resolution; 153)
[2024-02-05T11:00:41.823+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-05T11:00:41.853+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
