[2024-01-24T00:58:23.284+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerDag3.tsk2 manual__2024-01-24T00:58:21.429886+00:00 [queued]>
[2024-01-24T00:58:23.300+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerDag3.tsk2 manual__2024-01-24T00:58:21.429886+00:00 [queued]>
[2024-01-24T00:58:23.300+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T00:58:23.300+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-24T00:58:23.301+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T00:58:23.333+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-01-24 00:58:21.429886+00:00
[2024-01-24T00:58:23.341+0000] {standard_task_runner.py:55} INFO - Started process 2718 to run task
[2024-01-24T00:58:23.346+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerDag3', 'tsk2', 'manual__2024-01-24T00:58:21.429886+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmpan62a1lg']
[2024-01-24T00:58:23.347+0000] {standard_task_runner.py:83} INFO - Job 44: Subtask tsk2
[2024-01-24T00:58:23.457+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerDag3.tsk2 manual__2024-01-24T00:58:21.429886+00:00 [running]> on host cd1b9fd02609
[2024-01-24T00:58:23.615+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerDag3
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T00:58:21.429886+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-24T00:58:21.429886+00:00
[2024-01-24T00:58:23.616+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T00:58:23.617+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-24T00:58:23.638+0000] {subprocess.py:86} INFO - Output:
[2024-01-24T00:58:23.639+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T00:58:23.664+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T00:58:23.672+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerDag3, task_id=tsk2, execution_date=20240124T005821, start_date=20240124T005823, end_date=20240124T005823
[2024-01-24T00:58:23.700+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 44 for task tsk2 (Bash command failed. The command returned a non-zero exit code 1.; 2718)
[2024-01-24T00:58:23.726+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-24T00:58:23.787+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
